In [440]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [441]:
data=pd.read_csv("Mall_Customers.csv")
X=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values
print(X)
print(y)

[['Male' 19 15]
 ['Male' 21 15]
 ['Female' 20 16]
 ['Female' 23 16]
 ['Female' 31 17]
 ['Female' 22 17]
 ['Female' 35 18]
 ['Female' 23 18]
 ['Male' 64 19]
 ['Female' 30 19]
 ['Male' 67 19]
 ['Female' 35 19]
 ['Female' 58 20]
 ['Female' 24 20]
 ['Male' 37 20]
 ['Male' 22 20]
 ['Female' 35 21]
 ['Male' 20 21]
 ['Male' 52 23]
 ['Female' 35 23]
 ['Male' 35 24]
 ['Male' 25 24]
 ['Female' 46 25]
 ['Male' 31 25]
 ['Female' 54 28]
 ['Male' 29 28]
 ['Female' 45 28]
 ['Male' 35 28]
 ['Female' 40 29]
 ['Female' 23 29]
 ['Male' 60 30]
 ['Female' 21 30]
 ['Male' 53 33]
 ['Male' 18 33]
 ['Female' 49 33]
 ['Female' 21 33]
 ['Female' 42 34]
 ['Female' 30 34]
 ['Female' 36 37]
 ['Female' 20 37]
 ['Female' 65 38]
 ['Male' 24 38]
 ['Male' 48 39]
 ['Female' 31 39]
 ['Female' 49 39]
 ['Female' 24 39]
 ['Female' 50 40]
 ['Female' 27 40]
 ['Female' 29 40]
 ['Female' 31 40]
 ['Female' 49 42]
 ['Male' 33 42]
 ['Female' 31 43]
 ['Male' 59 43]
 ['Female' 50 43]
 ['Male' 47 43]
 ['Female' 51 44]
 ['Male' 69 44]


In [442]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [443]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[:,1:] = sc.fit_transform(X[:,1:])
print(X)

[[0.0 1.1281521496355316 -1.4245687900521389 -1.7389991930659479]
 [0.0 1.1281521496355316 -1.2810354107017976 -1.7389991930659479]
 [1.0 -0.8864052604279177 -1.3528021003769684 -1.7008297638941756]
 [1.0 -0.8864052604279177 -1.137502031351456 -1.7008297638941756]
 [1.0 -0.8864052604279177 -0.5633685139500902 -1.6626603347224032]
 [1.0 -0.8864052604279177 -1.2092687210266269 -1.6626603347224032]
 [1.0 -0.8864052604279177 -0.27630175524940737 -1.624490905550631]
 [1.0 -0.8864052604279177 -1.137502031351456 -1.624490905550631]
 [0.0 1.1281521496355316 1.8049322453305436 -1.5863214763788585]
 [1.0 -0.8864052604279177 -0.635135203625261 -1.5863214763788585]
 [0.0 1.1281521496355316 2.020232314356056 -1.5863214763788585]
 [1.0 -0.8864052604279177 -0.27630175524940737 -1.5863214763788585]
 [1.0 -0.8864052604279177 1.3743321072795194 -1.5481520472070862]
 [1.0 -0.8864052604279177 -1.0657353416762854 -1.5481520472070862]
 [0.0 1.1281521496355316 -0.13276837589906595 -1.5481520472070862]
 [0.0 

In [444]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [445]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 5, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=5, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [446]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[12.   29.  ]
 [26.8  13.  ]
 [51.   46.  ]
 [51.2  42.  ]
 [82.8  69.  ]
 [27.8  15.  ]
 [77.   76.  ]
 [24.6  36.  ]
 [19.   15.  ]
 [15.2  20.  ]
 [60.4  55.  ]
 [56.2  77.  ]
 [23.6  32.  ]
 [20.2  16.  ]
 [49.   51.  ]
 [77.   94.  ]
 [69.6  92.  ]
 [33.2   9.  ]
 [79.6  73.  ]
 [49.   47.  ]
 [74.   88.  ]
 [60.8  97.  ]
 [76.   65.  ]
 [78.   73.  ]
 [49.4  56.  ]
 [77.6  91.  ]
 [58.63 90.  ]
 [79.2  97.  ]
 [57.4  58.  ]
 [35.8  28.  ]
 [81.4  35.  ]
 [47.   41.  ]
 [22.2  17.  ]
 [46.8  54.  ]
 [31.8   5.  ]
 [48.8  85.  ]
 [61.4  75.  ]
 [60.2  40.  ]
 [46.   44.  ]
 [47.8  50.  ]]


In [447]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.6294621784519341